import { addDays, formatISO, subDays } from "date-fns";

import type {
  AIInteraction,
  Appointment,
  AutomationSetting,
  BoardingStay,
  Customer,
  DemoWorkspaceState,
  Message,
  MissedCall,
  Organization,
  Payment,
  Pet,
  Reminder,
  Service,
  SetupWorkspacePayload,
  StaffMember,
} from "@/lib/types";

const today = new Date();
const dateOnly = (value: Date) => formatISO(value, { representation: "date" });
const iso = (value: Date) => value.toISOString();

const organization: Organization = {
  id: "org_zion",
  name: "Zion & Co. Grooming Lodge",
  workspaceMode: "demo",
  brand: {
    businessName: "Zion & Co. Grooming Lodge",
    businessSlug: "zion-and-co-grooming-lodge",
    logoUrl: "/Zion -Groom-Lodge.png",
    primaryColor: "#79c6bf",
    secondaryColor: "#fff5ef",
    accentColor: "#f2b7c6",
    neutralColor: "#3d3a39",
    roundedScale: "26px",
    poweredByPawFlow: true,
    portalHeadline: "Book polished grooming and cozy boarding in one place.",
    portalSubcopy:
      "Share your pet's routine once, keep vaccine records tidy, and stay updated without chasing texts.",
    notificationSignature: "Warmly, the Zion & Co. front desk",
  },
  hours: [
    "Mon-Fri: 8:00 AM - 6:00 PM",
    "Sat: 8:00 AM - 4:00 PM",
    "Sun: Boarding pick-up only 10:00 AM - 1:00 PM",
  ],
  cancellationPolicy: "48-hour notice required for grooming. Same-day no-shows may be charged a fee.",
  depositPolicy: "Deposits required for first visits, long grooms, and holiday boarding.",
  boardingCapacity: 18,
  vaccineRequirements: [
    "Rabies",
    "Bordetella",
    "DHPP",
    "Canine influenza recommended for daycare",
  ],
  aiGuardrails: [
    "Do not make medical claims.",
    "Ask for vaccine records for boarding/daycare.",
    "Escalate urgent or aggressive behavior concerns to staff.",
  ],
};

const staff: StaffMember[] = [
  {
    id: "staff_amelia",
    organizationId: organization.id,
    name: "Amelia Hart",
    roleLabel: "Owner",
    specialty: "Operations + poodle trims",
    avatar: "AH",
    phone: "(615) 555-0141",
    color: "#79c6bf",
    isAvailableToday: true,
  },
  {
    id: "staff_kayla",
    organizationId: organization.id,
    name: "Kayla Monroe",
    roleLabel: "Front Desk",
    specialty: "Scheduling + customer care",
    avatar: "KM",
    phone: "(615) 555-0130",
    color: "#f2b7c6",
    isAvailableToday: true,
  },
  {
    id: "staff_jules",
    organizationId: organization.id,
    name: "Jules Rivera",
    roleLabel: "Senior Groomer",
    specialty: "Doodles + desheds",
    avatar: "JR",
    phone: "(615) 555-0192",
    color: "#ffd58a",
    isAvailableToday: true,
  },
];

const services: Service[] = [
  {
    id: "svc_groom",
    organizationId: organization.id,
    name: "Full Groom",
    category: "grooming",
    durationMinutes: 150,
    price: 115,
    depositRequired: true,
    depositAmount: 25,
    description: "Bath, blowout, haircut, nails, ears, and finishing spray.",
  },
  {
    id: "svc_tidy",
    organizationId: organization.id,
    name: "Mini Tidy",
    category: "grooming",
    durationMinutes: 75,
    price: 65,
    depositRequired: false,
    depositAmount: 0,
    description: "Face, feet, and sanitary trim with light fluff refresh.",
  },
  {
    id: "svc_deshed",
    organizationId: organization.id,
    name: "Deshed Spa",
    category: "grooming",
    durationMinutes: 120,
    price: 95,
    depositRequired: false,
    depositAmount: 0,
    description: "Deep coat release treatment for heavy shedders.",
  },
  {
    id: "svc_board",
    organizationId: organization.id,
    name: "Overnight Boarding",
    category: "boarding",
    durationMinutes: 1440,
    price: 78,
    depositRequired: true,
    depositAmount: 50,
    description: "Suite stay with potty breaks, cozy bedding, and photo updates.",
  },
];

const customers: Customer[] = [
  {
    id: "cust_olivia",
    organizationId: organization.id,
    name: "Olivia Bennett",
    phone: "(615) 555-0101",
    email: "olivia.bennett@example.com",
    preferredChannel: "sms",
    tags: ["VIP", "rebooks ahead"],
    notes: ["Prefers early drop-off before work."],
    balanceCents: 0,
    lastVisitAt: dateOnly(subDays(today, 4)),
  },
  {
    id: "cust_sarah",
    organizationId: organization.id,
    name: "Sarah Collins",
    phone: "(615) 555-0171",
    email: "sarah.collins@example.com",
    preferredChannel: "sms",
    tags: ["boarding"],
    notes: ["Needs vaccine reminders before every stay."],
    balanceCents: 3200,
    lastVisitAt: dateOnly(subDays(today, 42)),
  },
  {
    id: "cust_megan",
    organizationId: organization.id,
    name: "Megan Price",
    phone: "(615) 555-0124",
    email: "megan.price@example.com",
    preferredChannel: "email",
    tags: ["nervous pet"],
    notes: ["Max does better with text updates."],
    balanceCents: 1800,
    lastVisitAt: dateOnly(subDays(today, 18)),
  },
  {
    id: "cust_lauren",
    organizationId: organization.id,
    name: "Lauren West",
    phone: "(615) 555-0185",
    email: "lauren.west@example.com",
    preferredChannel: "sms",
    tags: ["reactivation"],
    notes: ["Usually books every 5-6 weeks."],
    balanceCents: 0,
    lastVisitAt: dateOnly(subDays(today, 60)),
  },
];

const pets: Pet[] = [
  {
    id: "pet_zion",
    organizationId: organization.id,
    customerId: "cust_olivia",
    name: "Zion",
    breed: "Standard Poodle",
    age: "4 years",
    weight: "53 lb",
    allergies: ["Chicken treats"],
    groomingNotes: [
      {
        id: "gn_1",
        petId: "pet_zion",
        createdAt: iso(subDays(today, 28)),
        stylist: "Amelia Hart",
        note: "Keep topknot airy, round feet, leave tail plume fluffy.",
        cutPreference: "Modern teddy trim, #1 comb on body",
        sameAsLastTime: true,
      },
    ],
    behaviorAlerts: [
      { id: "ba_1", petId: "pet_zion", label: "Sensitive front legs", severity: "medium" },
    ],
    vaccineRecords: [
      {
        id: "vr_1",
        petId: "pet_zion",
        name: "Rabies",
        expiresAt: dateOnly(addDays(today, 120)),
        status: "current",
        uploadedBy: "Olivia Bennett",
      },
      {
        id: "vr_2",
        petId: "pet_zion",
        name: "Bordetella",
        expiresAt: dateOnly(addDays(today, 20)),
        status: "expiring-soon",
        uploadedBy: "Olivia Bennett",
      },
    ],
    cutPreferences: "Elegant poodle shape with plush legs.",
    boardingNotes: "Sleeps with a blanket and white noise.",
    sameAsLastTime: "Use the spring lamb trim from March.",
    lastVisitAt: dateOnly(subDays(today, 4)),
  },
  {
    id: "pet_ronnie",
    organizationId: organization.id,
    customerId: "cust_olivia",
    name: "Ronnie",
    breed: "Mini Poodle",
    age: "2 years",
    weight: "16 lb",
    allergies: [],
    groomingNotes: [],
    behaviorAlerts: [],
    vaccineRecords: [
      {
        id: "vr_3",
        petId: "pet_ronnie",
        name: "Rabies",
        expiresAt: dateOnly(addDays(today, 180)),
        status: "current",
        uploadedBy: "Olivia Bennett",
      },
    ],
    cutPreferences: "Keep ears longer and cheeks round.",
    boardingNotes: "Can be vocal at bedtime.",
    sameAsLastTime: "Shorter face, fuller ears.",
    lastVisitAt: dateOnly(subDays(today, 10)),
  },
  {
    id: "pet_bella",
    organizationId: organization.id,
    customerId: "cust_sarah",
    name: "Bella",
    breed: "Golden Retriever",
    age: "6 years",
    weight: "62 lb",
    allergies: ["Grain-heavy biscuits"],
    groomingNotes: [],
    behaviorAlerts: [{ id: "ba_2", petId: "pet_bella", label: "Dry skin", severity: "low" }],
    vaccineRecords: [
      {
        id: "vr_4",
        petId: "pet_bella",
        name: "Bordetella",
        expiresAt: dateOnly(subDays(today, 5)),
        status: "expired",
        uploadedBy: "Sarah Collins",
      },
    ],
    cutPreferences: "Tidy feet and feathering, no heavy trim.",
    boardingNotes: "Loves frozen lick mat at night.",
    sameAsLastTime: "Deshed package with feather tidy.",
    lastVisitAt: dateOnly(subDays(today, 42)),
  },
  {
    id: "pet_max",
    organizationId: organization.id,
    customerId: "cust_megan",
    name: "Max",
    breed: "French Bulldog",
    age: "3 years",
    weight: "24 lb",
    allergies: ["Peanut butter"],
    groomingNotes: [],
    behaviorAlerts: [{ id: "ba_3", petId: "pet_max", label: "Anxious with dryers", severity: "high" }],
    vaccineRecords: [
      {
        id: "vr_5",
        petId: "pet_max",
        name: "Rabies",
        expiresAt: dateOnly(addDays(today, 240)),
        status: "current",
        uploadedBy: "Megan Price",
      },
    ],
    cutPreferences: "Quick nail grind, scent-free products.",
    boardingNotes: "Needs cool room and slower walk pace.",
    sameAsLastTime: "Same as last time",
    lastVisitAt: dateOnly(subDays(today, 18)),
  },
  {
    id: "pet_daisy",
    organizationId: organization.id,
    customerId: "cust_lauren",
    name: "Daisy",
    breed: "Doodle",
    age: "5 years",
    weight: "48 lb",
    allergies: [],
    groomingNotes: [],
    behaviorAlerts: [],
    vaccineRecords: [
      {
        id: "vr_6",
        petId: "pet_daisy",
        name: "Rabies",
        expiresAt: dateOnly(addDays(today, 90)),
        status: "current",
        uploadedBy: "Lauren West",
      },
    ],
    cutPreferences: "Plush doodle face, leave lashes.",
    boardingNotes: "Bring own food only.",
    sameAsLastTime: "Same fluffy face as January.",
    lastVisitAt: dateOnly(subDays(today, 60)),
  },
  {
    id: "pet_luna",
    organizationId: organization.id,
    customerId: "cust_sarah",
    name: "Luna",
    breed: "Husky",
    age: "4 years",
    weight: "55 lb",
    allergies: [],
    groomingNotes: [],
    behaviorAlerts: [{ id: "ba_4", petId: "pet_luna", label: "Talkative in kennel", severity: "low" }],
    vaccineRecords: [
      {
        id: "vr_7",
        petId: "pet_luna",
        name: "Bordetella",
        expiresAt: dateOnly(addDays(today, 8)),
        status: "expiring-soon",
        uploadedBy: "Sarah Collins",
      },
    ],
    cutPreferences: "No shave, deshed only.",
    boardingNotes: "Needs double latch check.",
    sameAsLastTime: "Full deshed with blueberry facial.",
    lastVisitAt: dateOnly(subDays(today, 24)),
  },
];

const appointments: Appointment[] = [
  {
    id: "appt_1",
    organizationId: organization.id,
    customerId: "cust_olivia",
    petId: "pet_zion",
    staffId: "staff_amelia",
    serviceId: "svc_groom",
    date: dateOnly(today),
    startTime: "08:30",
    endTime: "11:00",
    price: 125,
    deposit: 25,
    status: "checked-in",
    notes: "Keep plush legs and shorter muzzle.",
    noShowRisk: "low",
    reminderEnabled: true,
  },
  {
    id: "appt_2",
    organizationId: organization.id,
    customerId: "cust_megan",
    petId: "pet_max",
    staffId: "staff_jules",
    serviceId: "svc_tidy",
    date: dateOnly(today),
    startTime: "10:00",
    endTime: "11:15",
    price: 65,
    deposit: 0,
    status: "confirmed",
    notes: "Text when ready, sensitive to dryer noise.",
    noShowRisk: "medium",
    reminderEnabled: true,
  },
  {
    id: "appt_3",
    organizationId: organization.id,
    customerId: "cust_sarah",
    petId: "pet_bella",
    staffId: "staff_jules",
    serviceId: "svc_deshed",
    date: dateOnly(today),
    startTime: "01:00",
    endTime: "03:00",
    price: 95,
    deposit: 0,
    status: "requested",
    notes: "Needs vaccine check before daycare add-on.",
    noShowRisk: "high",
    reminderEnabled: true,
  },
  {
    id: "appt_4",
    organizationId: organization.id,
    customerId: "cust_lauren",
    petId: "pet_daisy",
    staffId: "staff_amelia",
    serviceId: "svc_groom",
    date: dateOnly(addDays(today, 2)),
    startTime: "09:00",
    endTime: "11:30",
    price: 118,
    deposit: 25,
    status: "confirmed",
    notes: "Same fluff as last time.",
    noShowRisk: "medium",
    reminderEnabled: true,
  },
];

const boardingStays: BoardingStay[] = [
  {
    id: "stay_1",
    organizationId: organization.id,
    customerId: "cust_sarah",
    petId: "pet_luna",
    room: "Suite B2",
    startDate: dateOnly(today),
    endDate: dateOnly(addDays(today, 3)),
    status: "checked-in",
    feedingNotes: "1 cup twice daily, slow feeder only.",
    medicationNotes: "Joint supplement at dinner.",
    vaccineStatus: "attention",
    photoUpdates: ["Sunset yard photo sent yesterday."],
  },
  {
    id: "stay_2",
    organizationId: organization.id,
    customerId: "cust_olivia",
    petId: "pet_ronnie",
    room: "Cottage A1",
    startDate: dateOnly(addDays(today, 5)),
    endDate: dateOnly(addDays(today, 7)),
    status: "confirmed",
    feedingNotes: "Bring lamb kibble.",
    medicationNotes: "None.",
    vaccineStatus: "clear",
    photoUpdates: [],
  },
];

const payments: Payment[] = [
  {
    id: "pay_1",
    organizationId: organization.id,
    customerId: "cust_olivia",
    appointmentId: "appt_1",
    amount: 125,
    depositAmount: 25,
    status: "partial",
    method: "card",
    dueDate: dateOnly(today),
    label: "Zion full groom",
  },
  {
    id: "pay_2",
    organizationId: organization.id,
    customerId: "cust_sarah",
    boardingStayId: "stay_1",
    amount: 234,
    depositAmount: 50,
    status: "unpaid",
    method: "square",
    dueDate: dateOnly(addDays(today, 3)),
    label: "Luna boarding balance",
  },
  {
    id: "pay_3",
    organizationId: organization.id,
    customerId: "cust_megan",
    appointmentId: "appt_2",
    amount: 65,
    depositAmount: 0,
    status: "unpaid",
    method: "stripe",
    dueDate: dateOnly(today),
    label: "Max mini tidy",
  },
];

const messages: Message[] = [
  {
    id: "msg_1",
    organizationId: organization.id,
    customerId: "cust_megan",
    petId: "pet_max",
    channel: "sms",
    direction: "inbound",
    subject: "Arrival question",
    body: "Running 10 minutes late for Max. Is that okay?",
    createdAt: iso(subDays(today, 0)),
    sender: "Megan Price",
    status: "received",
  },
  {
    id: "msg_2",
    organizationId: organization.id,
    customerId: "cust_sarah",
    petId: "pet_bella",
    channel: "email",
    direction: "outbound",
    subject: "Bordetella reminder",
    body: "Bella's Bordetella vaccine has expired. Upload an update before boarding or daycare.",
    createdAt: iso(subDays(today, 1)),
    sender: "PawFlow Automations",
    status: "sent",
  },
];

const reminders: Reminder[] = [
  {
    id: "rem_1",
    organizationId: organization.id,
    type: "vaccine",
    petId: "pet_bella",
    customerId: "cust_sarah",
    dueAt: iso(today),
    status: "queued",
    message: "Bella needs an updated Bordetella vaccine before daycare or boarding.",
  },
  {
    id: "rem_2",
    organizationId: organization.id,
    type: "reactivation",
    petId: "pet_daisy",
    customerId: "cust_lauren",
    dueAt: iso(today),
    status: "draft",
    message: "We miss Daisy's fluffy face. Want to grab her usual doodle refresh?",
  },
];

const aiInteractions: AIInteraction[] = [
  {
    id: "ai_1",
    organizationId: organization.id,
    task: "summarizeDay",
    inputSummary: "Morning appointments, boarding occupancy, missed calls",
    output:
      "Full groom traffic is heavy before lunch, Luna's boarding stay needs vaccine follow-up, and Max may arrive late.",
    createdAt: iso(today),
  },
];

const automations: AutomationSetting[] = [
  {
    id: "auto_1",
    key: "appointment-reminders",
    title: "Appointment reminders",
    description: "Send day-before and morning-of reminders with prep notes.",
    enabled: true,
  },
  {
    id: "auto_2",
    key: "missed-call-text-back",
    title: "Missed-call text-back",
    description: "Rescue missed calls with AI-written text replies and intake capture.",
    enabled: true,
  },
  {
    id: "auto_3",
    key: "vaccine-expiration",
    title: "Vaccine expiration reminders",
    description: "Flag expired or soon-to-expire vaccines before boarding and daycare.",
    enabled: true,
  },
  {
    id: "auto_4",
    key: "no-show-follow-up",
    title: "No-show follow-up",
    description: "Send gentle reschedule nudges after missed visits.",
    enabled: false,
  },
  {
    id: "auto_5",
    key: "rebooking-reminders",
    title: "Rebooking reminders",
    description: "Spot pets drifting past their usual cadence and bring them back.",
    enabled: true,
  },
  {
    id: "auto_6",
    key: "birthday-messages",
    title: "Birthday / gotcha day messages",
    description: "Celebrate special dates with boutique-feeling notes and perks.",
    enabled: false,
  },
  {
    id: "auto_7",
    key: "review-requests",
    title: "Review requests",
    description: "Trigger review asks after completed appointments and stays.",
    enabled: true,
  },
  {
    id: "auto_8",
    key: "lapsed-reactivation",
    title: "Lapsed customer reactivation",
    description: "Generate 'We miss Bella' campaigns for customers who slipped away.",
    enabled: true,
  },
  {
    id: "auto_9",
    key: "first-time-onboarding",
    title: "First-time customer onboarding",
    description: "Send prep notes, directions, and what-to-expect messages.",
    enabled: true,
  },
  {
    id: "auto_10",
    key: "boarding-photo-updates",
    title: "Boarding photo update reminders",
    description: "Prompt staff to share photo updates during longer stays.",
    enabled: true,
  },
];

const missedCalls: MissedCall[] = [
  {
    id: "call_1",
    customerName: "Emily Stone",
    phone: "(615) 555-0167",
    summary: "Asked about doodle grooming pricing for next week.",
    intent: "pricing",
    textBack:
      "Hi Emily, thanks for calling Zion & Co. We can help with doodle grooming and share pricing by coat size. What size is your pup and which days next week work best?",
    createdAt: iso(today),
  },
];

export function createDemoWorkspace(): DemoWorkspaceState {
  return {
    organization,
    staff,
    services,
    customers,
    pets,
    appointments,
    boardingStays,
    payments,
    messages,
    reminders,
    intakeRequests: [],
    aiInteractions,
    automations,
    missedCalls,
  };
}

export function createStarterWorkspace(payload: SetupWorkspacePayload): DemoWorkspaceState {
  const base = createDemoWorkspace();
  const organizationId = base.organization.id;

  return {
    ...base,
    organization: {
      ...base.organization,
      name: payload.businessName,
      workspaceMode: "custom",
      brand: {
        ...base.organization.brand,
        businessName: payload.businessName,
        businessSlug: payload.businessSlug,
        logoUrl: payload.logoUrl,
        primaryColor: payload.primaryColor,
        secondaryColor: payload.secondaryColor,
        accentColor: payload.accentColor,
        portalHeadline:
          payload.portalHeadline ||
          `Welcome to ${payload.businessName}. Book care, message the front desk, and keep your pet details in one place.`,
        notificationSignature: `Warmly, the ${payload.businessName} team`,
      },
      hours: payload.hours,
      boardingCapacity: payload.boardingCapacity,
      cancellationPolicy: payload.cancellationPolicy,
      depositPolicy: payload.depositPolicy,
      vaccineRequirements: payload.vaccineRequirements,
      aiGuardrails: payload.aiGuardrails,
    },
    services: payload.services.map((service, index) => ({
      id: `svc_custom_${index + 1}`,
      organizationId,
      name: service.name,
      category: service.category,
      durationMinutes: service.durationMinutes,
      price: service.price,
      depositRequired: service.depositAmount > 0,
      depositAmount: service.depositAmount,
      description: `${service.name} for ${payload.businessName}.`,
    })),
    staff: payload.staff.map((staffMember, index) => ({
      id: `staff_custom_${index + 1}`,
      organizationId,
      name: staffMember.name,
      roleLabel: staffMember.roleLabel,
      specialty: staffMember.specialty,
      avatar: staffMember.name
        .split(" ")
        .slice(0, 2)
        .map((part) => part[0])
        .join("")
        .toUpperCase(),
      phone: "",
      color: [payload.primaryColor, payload.accentColor, "#ffd58a"][index % 3],
      isAvailableToday: true,
    })),
    customers: [],
    pets: [],
    appointments: [],
    boardingStays: [],
    payments: [],
    messages: [],
    reminders: [],
    intakeRequests: [],
    aiInteractions: [],
    missedCalls: [],
  };
}
